### ISSUE TITLE
hey there!

### ISSUE THREAD

**Issue by BurningTreeC** [hendricius/pizza-dough#11]
hello and congratulations to this great repository! 👍 

as it happens to be, I live ~20 kilometres (that's some miles less) from the Pizzeria Panorama in the german-speaking SouthTyrol, Italy. Now, if you want me to, I can ask them anytime soon about how they make it. If not, they may just be interested that there's a github repository about their pizza-dough, which is awesome 😁 !

I'll try your recipe anytime soon, thank you!

cheers, BTC

**Comment by BurningTreeC** [comment]
Actually, the best pizza I've ever had was in Hamburg during a bachelor-farewell trip, we've been drunk all the time, that's why nobody believes my stories about the best pizza I ever had. But try the Margherita at the River Kasematten (I believe) - somewhere at the Fischmarkt. Have some beers first, you better start at midday drinking, then at 5 - 6 pm have a pizza and then have another one, that resembles the original states. Then you may report back

**Comment by hendricius** [comment]
Wow - living in Hamburg. I didn't know this place. That looks amazing indeed. I'll go there on the weekend.

Valdaora - oh yes, that would be amazing. Tell them a German from Hamburg, who didn't visit last year unfortunately. A family of Mom, Dad, Son + Girlfriend. In the past 2 sisters joined. Go for a simple pizza Margherita. Take a seat so that you can see how the chef works the dough, he's really good.

**Comment by hendricius** [comment]
Btw. I went to the restaurant. It was amazing. Thanks for the tip!
