### ISSUE TITLE
Fresh/dry yeast in calculator

### ISSUE THREAD

**Issue by henrikekblad** [hendricius/pizza-dough#31]
Shouldn't the calculator show the amount of dry respectively fresh yeast to be used?

I almost made a mistake when doing my first 10 pizza batch. :)

**Comment by painavin** [comment]
Yes

**Comment by Viper9087** [comment]
How has nobody noticed that the yeast percentage is messed up?     .05%???   5/100ths of a percent.
   
.05% is roughly .25 grams per 4 cups flour, which is about 1/4 packet of sweet n low.   About a pinch...  
  
A pinch of yeast is incorrect.    
   
A packet of yeast 1gram    is about 1/8 teaspoons, which is about .5%   
   
Somebody needs to put their decimal places in the right spot

**Comment by hendricius** [comment]
@Viper9087 where did you find this error? It's indeed that low of a percentage :).

**Comment by hendricius** [comment]
@henrikekblad that would be nice to add indeed.

**Comment by Viper9087** [comment]
I explained the error.   
The number you are looking is .5% or (1/2 of a percent)  this is equal to about one yeast packet.
.05% (5/100th of a percent) is less than one pinch of yeast.

**Comment by hendricius** [comment]
@Viper9087 could you please create a pull request to correct what you think is wrong? Thanks! Appreciated.

**Comment by Viper9087** [comment]
yeah, I don't know how to do that.  Thought I explained it simply enough.
HERE:

```
**Ingredients**

To the novice pizza baker it is surprising how few ingredients you need to make a pizza dough. The quantities of ingredients are specified as percentages of the mass of the flour that you use:

    Flour
    65.00% Warm Water
    2.00% Salt
    0.5% Dry yeast or 01.5% fresh yeast 
```        

(See:  Decimal places in correct place)

**Comment by henrikekblad** [comment]
Ok, created an PR
https://github.com/hendricius/pizza-dough/pull/34

**Comment by hendricius** [comment]
> yeah, I don't know how to do that. Thought I explained it simply enough.
> HERE:
> 
> ```
> **Ingredients**
> 
> To the novice pizza baker it is surprising how few ingredients you need to make a pizza dough. The quantities of ingredients are specified as percentages of the mass of the flour that you use:
> 
>     Flour
>     65.00% Warm Water
>     2.00% Salt
>     0.5% Dry yeast or 01.5% fresh yeast 
> ```
> 
> (See: Decimal places in correct place)

Thanks. But that is not correct. It is indeed 0.05% and 0.15% respectively. I have added a small pull request here: https://github.com/hendricius/pizza-dough/pull/35. Does it clarify the text?

Thanks for pointing this out, this is helpful feedback.

@henrikekblad good job that pull request, very helpful.

**Comment by Viper9087** [comment]
Sorry, but it is NOT correct.  I will explain using ONLY dry yeast calculations.

Link to an actual accurate yeast calculator. `https://www.traditionaloven.com/culinary-arts/baking/dry-instant-yeast/convert-gram-g-of-instant-yeast-to-tea-spoon-tsp.html` 
 
1 envelope (or packet) of Active Dry Yeast, Instant Yeast, Rapid Rise Yeast, Fast Rising Yeast or Bread Machine Yeast weighs 7 grams, or 1/4 ounce and equals 2 1/4 teaspoons (11 mL). 
 
Your calculator at .05% results in .12 grams of dry yeast for 2 pizzas @ 200 grams per pizza (your default)
  
(POINT-1-2!  that means you need almost 9 servings to equal one gram)  9 servings of .12grams equals only 1.08 grams 

1 dry yeast packet (7 grams) / .12 grams = 58.33   So your calculator is stating that 1 dry yeast packet is enough yeast for 58 pizzas.    

Please take a moment and think about this. 
   
https://percentagecalculator.net/
 
2 pizzas @200grams per pizza = 239.45g of flour (100%)
so then
7 grams (1 yeast packet) of 239.45g = 2.9233660471914806%  (rounded 3%)
This means that 1 yeast packet is 3% of 239.45g of flour (100%)
Now I'm not here to change your recipe... and tell you it should be 3%  
but it makes more sense than .05%   
   
5% would be roughly 1.33 yeast packets (just under 2 yeast packets for 2 pizzas) 
Which sounds more accurate than .12g or 12/100 or 12% of one gram 
which is:

and i think i just realized your confusion, you are writing/reading/saying it wrong.  
The problem seems that you are doing a percent of a percent)   .05 is 5% of 100 
writing .05% is not 5%     you are looking for either .05    OR   5%    NOT .05%   
(.05% means .0005 in decimals.)
the % sign means out of  100   or  /100   or  .(xx)
   
likewise your .15% should be 15 out of 100      OR 15 % using the same ideals.

You don't need the decimal when you use the % symbol.    its .00 OR % not  .00%
   
   
(oddly enough since I did the math I have now realized that you were off by 2 decimal places and not just one as I had previously assumed, so technically  I was wrong too)  
   
You are looking for:

<**Ingredients**

To the novice pizza baker it is surprising how few ingredients you need to make a pizza dough. The quantities of ingredients are specified as percentages of the mass of the flour that you use:

    Flour
    65.00% (65%) Warm Water
    2.00%   (2%)    Salt
    5.00%   (5%   ) Dry yeast or 15.00% (15%) fresh yeast >

**Comment by henrikekblad** [comment]
@Viper9087, have you tried the recipe? The dough rests for 24h, which means that the yest have plenty of time to develop in room temperature. Even this a small amount is enough. 

If you'd add 5% the dough would be "ready" in an hour... but not with with the flavors you'd get after 24h.

**Comment by Viper9087** [comment]
i have no scale that weighs 0.00
the one you have pictured seems to only do tenths (0.0) (could you link the name and model?) 
but by conversion: 
Amount of :  .12 grams (g of yeast)
Equals : 0.04 teaspoons (tsp / yeast)
Equals in Fraction : 1/25 teaspoons (tsp / yeast) 

1/8th of a teaspoon is a pinch.
So am I correct that you are saying that the correct amount of yeast for 2 pizzas is 1/3 of a pinch?
or 1/3 of 1/8th teaspoon?     an amount equal in volume to 1 corn kernel?

**Comment by Viper9087** [comment]
also equivalent to a pile the size of Lincoln's head on a penny?

**Comment by henrikekblad** [comment]
> the one you have pictured seems to only do tenths (0.0) (could you link the name and model?)

I bought this one: https://www.kitchenlab.se/produkt/diamantvag-vikter-om-001-500g-balance

**Comment by nabieasaurus** [comment]
Okay. I tried the recipe over the weekend with tiny amount of yeast (as compared to the packet of yeast that I usually use). The dough fermentation took really long time but in the end, it turned out better than what I had previously made.

**Comment by hendricius** [comment]
@henrikekblad wow - those pizzas look really amazing. Good job. I also recently tried the same recipe with an Ooni and the pizzas were super delicious. Thanks for sharing the pictures. Well done. Wish we could store them somewhere as pictures that have been baked using this recipe.

@Viper9087 glad we sorted out the issue. It's indeed very little yeast. The yeast reproduces over night. So you will end up having more yeast in the end. Slower fermentation creates more flavor, that's the secret.

@nabieasaurus glad it worked out fine!
